version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "*"
        update-types:
        - "version-update:semver-major"


  - package-ecosystem: docker
    directory: /tests
    schedule:
      interval: daily
