variables:
  amd.pool: staging-pool-amd64-mariner-2

stages:
  - stage: Validate
    jobs:
      - job: ValidateDataFormat
        pool: $(amd.pool)
        timeoutInMinutes: 5
        steps:
          - bash: |
              set -exu

              echo "$INPUT_DIR"
            displayName: Validate Input Data Format
            env:
              INPUT_DIR: "hello, world!"
