parameters:
  - name: str
    displayName: INPUT_<str>
    type: string
    default: ''

name: INPUT_${{ parameters.str }}

variables:
  amd.pool: staging-pool-amd64-mariner-2

stages:
  - stage: INPUT_${{ parameters.str }}
    jobs:
      - job: INPUT_${{ parameters.str }}
        pool: $(amd.pool)
        timeoutInMinutes: 5
        steps:
          - bash: |
              set -exu

              echo "$INPUT_${{ parameters.str }}"
            displayName: Validate Input Data Format
            env:
              INPUT_${{ parameters.str }}: "hello, world!"
