stages:
- stage: Sign
  condition: succeeded()
  jobs:
  - job: SignArtifacts
    pool: $(pool)
    workspace:
      clean: all
    steps:
    - checkout: none
    - download: current
      artifact: packages
    - task: UseDotNet@2
      displayName: Install .NET Core SDK
      inputs:
        packageType: sdk
        version: 2.2.207
    - template: sign.steps.yml
      parameters:
        folderPath: $(Pipeline.Workspace)/packages
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: "$(Pipeline.Workspace)/packages"
        artifactName: packages
