trigger: none

parameters:
  - name: storage_account_name
    displayName: Storage Account Name
    type: string
    default: moby
  - name: index_container
    displayName: Storage Container for storing index
    type: string
    default: index
  - name: rebuild
    displayName: Full index rebuild (destructive)
    type: boolean
    default: false

pool: production-pool-amd64-mariner-2

workspace:
  clean: all

steps:
  - checkout: self
  - bash: az login --identity
    displayName: Login to Azure
  - bash: scripts/generate-versions.sh
    displayName: Generate versions
    env:
      AZURE_STORAGE_ACCOUNT: ${{ parameters.storage_account_name }}
      STORAGE_CONTAINER: $(storage.account.container)
      OUTPUT: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: Store pipeline artifacts
    inputs:
      artifactName: versions
  - bash: |
      set -e

      az storage container create -n "${STORAGE_CONTAINER}" --auth-mode=login --public-access=blob


      if [ "${REBUILD_INDEX}" = "1" ]; then
        az storage blob delete-batch --source "${STORAGE_CONTAINER}" --auth-mode=login --pattern=*
      fi

      az storage blob upload-batch \
        --max-connections=10 --auth-mode=login \
        --overwrite \
        --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
        --destination "${STORAGE_CONTAINER}" \
        --destination-path "/" \
        --pattern "*.json" \
        --content-type "application/json"

      az storage blob upload-batch \
        --max-connections=10 --auth-mode=login \
        --overwrite \
        --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
        --destination "${STORAGE_CONTAINER}" \
        --destination-path "/" \
        --pattern "*.rss" \
        --content-type "application/rss+xml"

      az storage blob upload-batch \
        --max-connections=10 --auth-mode=login \
        --overwrite \
        --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
        --destination "${STORAGE_CONTAINER}" \
        --destination-path "/" \
        --pattern "**/latest/*" \
        --content-type "text/plain"

    displayName: Upload versions to blob storage
    env:
      AZURE_STORAGE_ACCOUNT: ${{ parameters.storage_account_name }}
      STORAGE_CONTAINER: ${{ parameters.index_container }}
      ${{ if eq(parameters.rebuild, 'true') }}:
        REBUILD_INDEX: "1"
